import dayjs from 'dayjs';
import * as db from '../database/db';
import type { MealEntry, WorkoutLog, DailyLog } from '../models';

const MEAL_OPTIONS = {
  Breakfast: [
    { desc: 'Oatmeal & Whey Protein', cal: 450, p: 35, f: 10, c: 55, fib: 8 },
    { desc: '3 Scrambled Eggs & Toast', cal: 400, p: 25, f: 22, c: 25, fib: 3 },
  ],
  Lunch: [
    { desc: 'Grilled Chicken Salad', cal: 550, p: 45, f: 25, c: 20, fib: 10 },
    { desc: 'Turkey Wrap & Apple', cal: 600, p: 40, f: 18, c: 65, fib: 7 },
  ],
  Dinner: [
    { desc: 'Salmon, Rice & Asparagus', cal: 700, p: 45, f: 30, c: 60, fib: 6 },
    { desc: 'Lean Steak & Sweet Potato', cal: 750, p: 55, f: 25, c: 70, fib: 8 },
  ],
  Snacks: [
    { desc: 'Greek Yogurt & Berries', cal: 200, p: 18, f: 4, c: 22, fib: 3 },
    { desc: 'Handful of Almonds', cal: 250, p: 9, f: 22, c: 8, fib: 4 },
  ],
};

const WORKOUT_OPTIONS = [
  { type: 'Weightlifting - Push', min: 60, cal: 350 },
  { type: 'Weightlifting - Pull', min: 60, cal: 350 },
  { type: 'Weightlifting - Legs', min: 75, cal: 450 },
  { type: 'Running 5k', min: 30, cal: 320 },
  { type: 'Cycling', min: 45, cal: 400 },
];

export async function seedTwoWeeksOfData(tdee: number = 2500) {
  console.log('🌱 Starting database seed for the last 14 days...');
  
  for (let i = 14; i >= 0; i--) {
    const date = dayjs().subtract(i, 'day').format('YYYY-MM-DD');
    console.log(`Seeding date: ${date}`);

    // 1. Initialize the daily log
    await db.getOrCreateDailyLog(date, tdee);
    
    // 2. Pick random meals
    const b = MEAL_OPTIONS.Breakfast[Math.floor(Math.random() * 2)];
    const l = MEAL_OPTIONS.Lunch[Math.floor(Math.random() * 2)];
    const d = MEAL_OPTIONS.Dinner[Math.floor(Math.random() * 2)];
    const s = MEAL_OPTIONS.Snacks[Math.floor(Math.random() * 2)];

    const mealsToInsert = [
      { category: 'Breakfast', ...b },
      { category: 'Lunch', ...l },
      { category: 'Dinner', ...d },
      { category: 'Evening Snack', ...s },
    ];

    let totalCal = 0, totalP = 0, totalF = 0, totalC = 0, totalFib = 0;

    for (const m of mealsToInsert) {
      await db.insertMealEntry({
        date,
        category: m.category,
        foodDescription: m.desc,
        calories: m.cal,
        protein: m.p,
        fat: m.f,
        carbs: m.c,
        fiber: m.fib,
      } as MealEntry);

      totalCal += m.cal;
      totalP += m.p;
      totalF += m.f;
      totalC += m.c;
      totalFib += m.fib;
    }

    // 3. 70% chance to have a workout on any given day (rest days are realistic!)
    let workoutCals = 0;
    if (Math.random() > 0.3) {
      const w = WORKOUT_OPTIONS[Math.floor(Math.random() * WORKOUT_OPTIONS.length)];
      await db.insertWorkout({
        date,
        exerciseType: w.type,
        durationMinutes: w.min,
        caloriesBurned: w.cal,
        notes: 'Generated by seeder',
      } as WorkoutLog);
      workoutCals = w.cal;
    }

    // 4. Update the Daily Log with the aggregated totals
    const existingLog = await db.getDailyLog(date);
    if (existingLog) {
      await db.updateDailyLog({
        ...existingLog,
        breakfastCal: b.cal,
        lunchCal: l.cal,
        dinnerCal: d.cal,
        eveningSnackCal: s.cal,
        workoutCalBurned: workoutCals,
        proteinTotal: totalP,
        fatTotal: totalF,
        carbsTotal: totalC,
        fiberTotal: totalFib,
      });
    }
  }

  console.log('✅ Seed complete! Reload your app to see the history.');
}